version: "3.8"
services:
  influxdb:
    image: influxdb
    environment:
      - TZ=Europe/Rome
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN='jcTCQ5PRSjOtj5ur0TkGc9y93aRYbO9yX7MN8l7D9_dWxc4rmDSnp5a7dSUNzhD3wAdSzVdZu2qCUsV5iaIwQg==' \
    ports:
      - "8086:8086"
    networks:
      - iot
    volumes:
      - influxdb/data:/var/lib/influxdb2
      - influxdb/config:/etc/influxdb2
    restart: always

  telegraf:
    image: telegraf
    user: "telegraf"
    environment:
      - TZ=Europe/Rome
    ports:
      - "8125:8125/udp"
    networks:
      - iot
    volumes:
      - telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
    restart: always
    
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    networks:
      - iot
    volumes:
      - grafana/data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - iot
    volumes:
      - mosquitto/:/mosquitto/
    restart: always

networks:
  iot:
